name: Linting and formatting on PR
on:
  pull_request:
    branches:
      - '**'
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  Continuous-Integration:
    name: Checking the build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run linting check
        run: pnpm run build
